version: '3'

services:
  client:
    build: ./src/client
    depends_on:
      - redis-service
    ports:
      - 8080:8080
    volumes:
      - ./src/client:/app
      - ./src/client/node_modules:/app/node_modules
  redis-service:
    image: redis:5-alpine
