version: '3'

services:
  client:
    build: ./src/client
    depends_on:
      - redis-service
    ports:
      - 8080:8080
    volumes:
      - ./src/client/node_modules:/app/node_modules
      - ./src/client:/app
  timer:
    build: ./src/timer
    depends_on:
      - redis-service
    ports:
      - 8081:8080
    volumes:
      - ./src/timer/node_modules:/app/node_modules
      - ./src/timer:/app
  redis-service:
    image: redis:5-alpine
