version: '3'

services:
  node:
    build: ./src
    depends_on:
      - redis-service
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
      - ./src/node_modules:/app/node_modules
  redis-service:
    image: redis:5-alpine
