version: '3'

services:
  client:
    build: ./src/client
    depends_on:
      - redis
      - server
    ports:
      - 8080:8080
    volumes:
      - ./src/client/node_modules:/app/node_modules
      - ./src/client:/app
  redis:
    image: redis:5-alpine
  server:
    build: ./src/server
    ports:
      - 8081:8080
    depends_on:
      - redis
    volumes:
      - ./src/server/node_modules:/app/node_modules
      - ./src/server:/app
  timer:
    build: ./src/timer
    depends_on:
      - redis
    volumes:
      - ./src/timer/node_modules:/app/node_modules
      - ./src/timer:/app
